### ISSUE TITLE
Can't set up 

### ISSUE THREAD

**Issue by samiashton1989** [zecure/shadowd_python#11]
I completed the installation and settings completed

  Error:
ANDLERS / BASE.PY ", LINE 58, IN LOAD_MIDDLEWARE
     mw_instance = middleware (adapted_handler)
TypeError: ShadowdconnectorMiddleware () Takes No Arguments

Can't Configuration.

/Etc/shadowd/connectors.ini folder does not exist

**Comment by zit-hb** [comment]
Can you post the code how you integrated the connector in the application? Also, what do you mean with "connectors.ini folder does not exist"? You have to create that manually.

**Comment by samiashton1989** [comment]
file middleware/shadowdconnector.py :

```
from shadowd.django_connector import InputDjango, OutputDjango, Connector
class ShadowdConnectorMiddleware(object):
    def process_request(self, request):
        input = InputDjango(request)
        output = OutputDjango()

        status = Connector().start(input, output)
        if not status == True:
            return status

file website/settings.py : 
MIDDLEWARE = [
    'middleware.shadowdconnector.ShadowdConnectorMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
```

  /etc/shadowd/connectors.ini  : 
```
[shadowd_python]
; Sets the address of the shadowd server.
; Default Value: 127.0.0.1 
```

**Comment by samiashton1989** [comment]
؟

**Comment by zit-hb** [comment]
Thanks for the code! It seems to be related to a newer Django version, I will release a fix on the weekend.

**Comment by samiashton1989** [comment]
Thanks for the answer

**Comment by samiashton1989** [comment]
django --version  2.2 
 dlers/base.py", line 37, in load_middleware
    mw_instance = middleware(handler)
TypeError: ShadowdConnectorMiddleware() takes no arguments

django --version 3.1.6
andlers/base.py", line 58, in load_middleware
    mw_instance = middleware(adapted_handler)
TypeError: ShadowdConnectorMiddleware() takes no arguments

I don't know where the problem is ?

**Comment by samiashton1989** [comment]
؟

**Comment by zit-hb** [comment]
The documentation is updated now to use the Django 4 format: https://shadowd.zecure.org/overview/python_connector/
