### ISSUE TITLE
Unable to sync from flask application to  deamon server. 

### ISSUE THREAD

**Issue by alankar1985** [zecure/shadowd_python#12]
Hi , 

I have setup server properly, trying to integrate it with one of my flask web application i faced below error.
1. port number is getting passed as string. 
Fix: for test type casted port as int in connector.py file 
int(config.get('port', default=9115)),
2. getting below error 
`  File "/usr/local/lib/python3.9/site-packages/shadowd/connector.py", line 264, in start
    status = connection.send(
  File "/usr/local/lib/python3.9/site-packages/shadowd/connector.py", line 209, in send
    return self.parse_output(output)
  File "/usr/local/lib/python3.9/site-packages/shadowd/connector.py", line 212, in parse_output
    data = json.loads(output)
  File "/usr/local/Cellar/python@3.9/3.9.1_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.9/3.9.1_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.9/3.9.1_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None`

I have checked all the values are fine but not sure about above error. i am also sharing test flask file 
```
from flask import Flask, request
from shadowd.flask_connector import InputFlask, OutputFlask, Connector
app = Flask(__name__)

@app.before_request
def before_req():
    # print('inputFlas'+str(request))
    input_pram = InputFlask(request)
    output_pram = OutputFlask()
    # print(str(output_pram))
    Connector().start(input_pram,output_pram)


@app.route('/')
def hello_world():
   return 'Hello World  '+str(request.args)

if __name__ == '__main__':
    app.debug = True
    app.run()
```

**Comment by zit-hb** [comment]
Hi @alankar1985 ,

Thanks for the report! It could be due to regression, I have not used nor updated the Python version for quite a while. I will try to debug it on the weekend.

**Comment by alankar1985** [comment]
Hi @zit-hb, 

Any update?

**Comment by zit-hb** [comment]
Hi @alankar1985 ,

I have started working on it but it is not finished yet.

**Comment by alankar1985** [comment]
Hi @zit-hb, any success.  If you tell me what we need to check, I can also try to finish it

**Comment by zit-hb** [comment]
Hi @alankar1985 ,

sorry for the delay! So far I was not able to reproduce this error or figure out why it is happening. It works fine for me with Python 3.9 and the latest version of Flask. Can you post the content of your `/etc/shadowd/connector.ini` (without password of course)? Maybe that will help, thanks!

**Comment by alankar1985** [comment]
![image](https://user-images.githubusercontent.com/9024816/155990922-124a917a-fcb4-46bc-9bbd-7bfaf19010bc.png)

Hi @zit-hb 
Please let me know if you need anyother details also i have a confusion, u asked for connector.ini but on my system it is saved as connectors.ini.

**Comment by zit-hb** [comment]
Hi @alankar1985, sorry for the confusion, it is indeed `connectors.ini`.

Okay, the error here is the port. You connect to the web interface, not to the shadowd server. Port 9115 is the one from shadowd that you have to use.
Since the connector does not connect to shadowd some unexpected data is returned, resulting in the parsing errors.

**Comment by alankar1985** [comment]
Means I need to use 9115 port instead of 8080?

**Comment by zit-hb** [comment]
Yes, exactly. You can just comment it out, 9115 is the default value as explained in the comment above.
