### ISSUE TITLE
error connecting to django

### ISSUE THREAD

**Issue by cristianfuente** [zecure/shadowd_python#14]
File "/usr/lib/python3.9/configparser.py", line 1152, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'shadowd_python'

**Comment by zit-hb** [comment]
This error means that there is no configuration file, or at least that it does not contain the section `shadowd_python`. How to set up the config is explained in the `Configuration` section at https://shadowd.zecure.org/overview/python_connector/.
