### ISSUE TITLE
configparser.NoSectionError: No section: 'shadowd_python'

### ISSUE THREAD

**Issue by lamweilun10** [zecure/shadowd_python#15]
Hi, i have installed shadow daemon on a centOS virtual machine, and I am running a flask application on my windows physical machine using pycharm. 
I understand that I need the connectors.ini file, where do I place the connectors.ini file? Placing it under my centOS virtual machine 'etc/shadowd/connectors.ini' doesn't seem to work, because the configparser error seems to be searching for the connectors.ini file in my windows computer.
I have followed the documentation, the only last piece of the puzzle is to figure out where do I point my flask application python connector to the connectors.ini file.
Please kindly help me out.

**Comment by zit-hb** [comment]
Hello,

the default location is `/etc/shadowd/connectors.ini`: https://github.com/zecure/shadowd_python/blob/v3.0.1/shadowd/connector.py#L30

You can override it using the env variable `SHADOWD_CONNECTOR_CONFIG`. Also, make sure that the config file is readable by your application.
