### ISSUE TITLE
error when setting port number 

### ISSUE THREAD

**Issue by melabady1** [zecure/shadowd_python#18]
Hello,
when added a customized port number in connectors.ini.
the config parser read it as string and then an exception is thrown in file shadowd/connector.py in line 264
status = connection.send(
                input,
                config.get('host', default='127.0.0.1'),
                config.get('port', default=9115),
                config.get('profile', required=True),
                config.get('key', required=True),
                config.get('ssl')
            )

as the port should  integer
i thing a type casting in missing here

Note:
i installed the connector using pip

**Comment by zit-hb** [comment]
Hello @melabady1 ,

A fix for this is already on the dev branch. I will release it soon.

**Comment by melabady1** [comment]
@zit-hb thank you
