### ISSUE TITLE
ConfigParser

### ISSUE THREAD

**Issue by h3r0cybersec** [zecure/shadowd_python#3]
Hi i'm tring to use this waf but at the present time i can't use it from python 3 because the ConfigParser module has changed name and it's called configparser so i receive ModuleNotFoundError when i try to run it. Can you please update

**Comment by zit-hb** [comment]
Hey. Thanks for the report, I will look at it on the weekend.

**Comment by h3r0cybersec** [comment]
thanks. However very good project.
