### ISSUE TITLE
No module named 'ConfigParser' i am getiing this error when i am trying to install pip install audio

### ISSUE THREAD

**Issue by ssruthireddy** [zecure/shadowd_python#9]
pip install audio

Collecting audio
  Downloading audio-1.5.0.tar.gz (2.1 kB)
Collecting audio.bitstream
  Downloading audio.bitstream-2.5.4.tar.gz (1.2 kB)
Collecting audio.coders
  Downloading audio.coders-4.0.2.tar.gz (682 kB)
     |████████████████████████████████| 682 kB 437 kB/s
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Jonathan Awofeso\anaconda3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\JON~1\\AppData\\Local\\Temp\\pip-install-eqao6bms\\audio-coders\\setup.py'"'"'; __file__='"'"'C:\\Users\\JON~1\\AppData\\Local\\Temp\\pip-install-eqao6bms\\audio-coders\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\JON~1\AppData\Local\Temp\pip-pip-egg-info-0ruwp_5p'
         cwd: C:\Users\JON~1\AppData\Local\Temp\pip-install-eqao6bms\audio-coders\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\JON~1\AppData\Local\Temp\pip-install-eqao6bms\audio-coders\setup.py", line 5, in <module>
        import ConfigParser
    ModuleNotFoundError: No module named 'ConfigParser'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by zit-hb** [comment]
Thanks for the report! I will have a look at it on the weekend.

**Comment by zit-hb** [comment]
The Python connector was for Python 2 only. I have now released version 3 of the connector for Python 3. If you install that one everything should work as expected.
